export const categories = [
  {
    name: { en: 'Smartphones & Accessories', rw: 'Telefoni & Ibicuruzwa' },
    slug: 'smartphones',
    image: 'https://placehold.co/400x300?text=Smartphones',
    featured: true,
    productCount: 15,
  },
  {
    name: { en: 'Computers & Laptops', rw: 'Kompyuta & Laptops' },
    slug: 'computers',
    image: 'https://placehold.co/400x300?text=Computers',
    featured: true,
    productCount: 12,
  },
  {
    name: { en: 'TVs & Audio', rw: 'TV & Ijwi' },
    slug: 'tvs',
    image: 'https://placehold.co/400x300?text=TVs+Audio',
    featured: true,
    productCount: 12,
  },
  {
    name: { en: 'Home Appliances', rw: 'Ibikoreswa mu Nzu' },
    slug: 'appliances',
    image: 'https://placehold.co/400x300?text=Appliances',
    featured: true,
    productCount: 12,
  },
  {
    name: { en: 'Wearables & Health', rw: 'Ibikoreswa byo Ku Mubiri & Ubuzima' },
    slug: 'wearables',
    image: 'https://placehold.co/400x300?text=Wearables',
    featured: true,
    productCount: 10,
  },
  {
    name: { en: 'Solar & Power', rw: 'Umucyo & Amashanyarazi' },
    slug: 'solar',
    image: 'https://placehold.co/400x300?text=Solar+Power',
    featured: true,
    productCount: 10,
  },
  {
    name: { en: 'Cameras & Creator Gear', rw: 'Foto & Ibikoreswa byo Kubika Videos' },
    slug: 'cameras',
    image: 'https://placehold.co/400x300?text=Cameras',
    featured: true,
    productCount: 10,
  },
  {
    name: { en: 'Electric Mobility', rw: 'Moto y\'Umuhanda' },
    slug: 'mobility',
    image: 'https://placehold.co/400x300?text=Mobility',
    featured: true,
    productCount: 10,
  },
  {
    name: { en: 'Security & Business', rw: 'Umutekano & Ibikorwa' },
    slug: 'security',
    image: 'https://placehold.co/400x300?text=Security',
    featured: true,
    productCount: 8,
  },
];
